### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by rask24** [rask24/tomi-portfolio#1]
## TODO
- [x] Create .nvmrc: ~v22~ v20
- [x] Setup eslint
- [x] Setup prettier
- [x] Setup Github Actions
- [x] Setup stylelint
- [x] Setup VSCode settings
- [x] Setup scripts in package.json
