### ISSUE TITLE
Create Directory Structure and Menu Configuration

### ISSUE THREAD

**Issue by rask24** [rask24/tomi-portfolio#12]
## TODO

- [x] Create the following directory structure under `app/`:
  - about/
  - request/
  - contact/
  - works/
    - design/
    - manga/
    - illustration/
    - sketch-and-painting/
    - line-stickers/
    - anime/
    - video-production/
    - video-editing/
    - others/
- [x] Create `src/config/` directory
- [x] Create `src/config/menuConfig.ts` with the following structure:
- [x] Create `layout.tsx`
