### ISSUE TITLE
Fix client side exception on smartphone

### ISSUE THREAD

**Issue by rask24** [rask24/tomi-portfolio#21]
## Description

Error message below was displayed on smartphone.
```
Invalid time value
Error: Minified React error #423; visit https://react.dev/errors/423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Load failed
Load failed
```

## TODO
- [x] Update formatDate
- [ ] Replace Date with string
- [ ] Replace ‘-‘ with ‘/‘ in Date string
- [ ] Revert formatDate and types
