### ISSUE TITLE
Configure colors and fonts

### ISSUE THREAD

**Issue by rask24** [rask24/tomi-portfolio#3]
## TODO

- [x] Update color scheme in `tailwind.config.ts`
- [x] Configure custom fonts in `tailwind.config.ts`
- [x] Add custom fonts to `public/fonts/` and configure in `globals.css`
- [x] Configure google fonts in layout.tsx
- [x] Test custom colors and fonts in a component
