### ISSUE TITLE
Create Home

### ISSUE THREAD

**Issue by rask24** [rask24/tomi-portfolio#7]
### TODO

- [x] Create PortfolioCard component
  - Display item image, title, and truncated description
  - Handle click event to show detailed view
- [x] Create PortfolioDetailModal component
  - Show full portfolio item details
  - Add internal and external links
  - Implement close button (X) in the top-right corner
  - Set appropriate z-index for overlay display
- [x] Implement PortfolioList to manage multiple PortfolioCards
- [x] Add state management for showing/hiding PortfolioDetailModal
